---
title: "CodeSimilarityCalculations"
author: "Alissa McGill"
date: "2026-05-27"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r Load all required packages, message=FALSE}

# load libraries
library(tidyr)
library(tidyverse)
library(dplyr)
library(psych)
library(ggplot2)
library(readxl)
library(uuid)
library(Hmisc)
library(lme4)
library(stringdist)
library(TopKLists)

```

```{r Load the data }


mckData = read.csv("mcKData_June10_2026.csv")

```

```{r Stimulus Code }

javaCode = c("public static void main() {",
             "int number1 = 20;",
             "int number2 = 15;",
             "System.out.print(compute(number1, number2));",
             "}",
             "public static int compute(int number1, int number2) {",
             "int temp = number1;",
             "while (temp != 0) {",
             "if (number1 < number2) {",
             "temp = number1;",
             "number1 = number2;",
             "number2 = temp;",
             "}",
             "temp = number1 % number2;",
             "if (temp != 0) {",
             "number1 = number2;",
             "number2 = temp;",
             "}",
             "}",
             "return number2;",
             "}")

javaScramble = c("return number2;",
                 "public static void main() {",
                 "number1 = number2;",
                 "int number2 = 15;",
                 "if (number1 < number2) {",
                 "while (temp != 0) {",
                 "}",
                 "int temp = number1;",
                 "temp = number1;",
                 "}",
                 "public static int compute(int number1, int number2) {",
                 "number2 = temp;",
                 "int number1 = 20;",
                 "temp = number1 % number2;",
                 "number1 = number2;",
                "System.out.print(compute(number1, number2));",
                "}",
                "if (temp != 0) {",
                "}",
                "number2 = temp;",
                "}")

cCode = c("int main() {",
         "int number1 = 20;",
         "int number2 = 15;",
         "cout << compute(number1, number2);",
         "}",
         "int compute(int number1, int number2) {",
         "int temp = number1;",
         "while (temp != 0) {",
         "if (number1 < number2) {",
         "temp = number1;",
         "number1 = number2;",
         "number2 = temp;",
         "}",
         "temp = number1 % number2;",
         "if (temp != 0) {",
         "number1 = number2;",
         "number2 = temp;",
         "}",
         "}",
         "return number2;",
         "}")

cScramble = c("return number2;",
              "int main() {",
              "number1 = number2;",
              "int number2 = 15;",
              "if (number1 < number2) {",
              "while (temp != 0) {",
              "}",
              "int temp = number1;",
              "temp = number1;",
              "}",
              "int compute(int number1, int number2) {",
              "number2 = temp;",
              "int number1 = 20;",
              "temp = number1 % number2;",
              "number1 = number2;",
              "cout << compute(number1, number2);",
              "}",
              "if (temp != 0) {",
              "}",
              "number2 = temp;",
              "}")
             

pythonCode = c("def main():",
               "number1 = 20",
               "number2 = 15",
               "print(compute(number1, number2))",
               "def compute(number1, number2):",
               "temp = number1",
               "while temp != 0:",
               "if number1 < number2:",
               "temp = number1",
               "number1 = number2",
               "number2 = temp",
               "temp = number1 % number2",
               "if temp != 0:",
               "number1 = number2",
               "number2 = temp",
               "return number2")


pythonScramble = c("return number2",
                   "def main():",
                   "number1 = number2",
                   "number2 = 15",
                   "if number1 < number2:",
                   "while temp != 0:",
                   "temp = number1",
                   "temp = number1",
                   "def compute(number1, number2):",
                   "number2 = temp",
                   "number1 = 20",
                   "temp = number1 % number2",
                   "number1 = number2",
                   "print(compute(number1, number2))",
                   "if temp != 0:",
                   "number2 = temp")

```

```{r Stimuli rank vectors }

# this is what we compare to for the foot rule.
# stimuli code is will be a vector with numbers from 1 to the max num of lines of code
javaRank = c(1:length(javaCode))

cRank = c(1:length(cCode))

pythonRank = c(1:length(pythonCode))


```

```{r Formula to calculate Levenshtein distance }
##returns a list with
#[1]the normalized average Levenshtein distance
#[2]mapping of the user Items to the stimuli Items
calculate_levdist <- function(stimCode, userCode)
{
 
  mapping = array(dim = length(stimCode))
  matchedStimuli = array(0, dim = length(stimCode))
  matchedUserCode = array(0, dim = length(userCode))
  
  final_LDs = array(dim = length(stimCode))
  normalfinal_LDs = array(dim = length(stimCode))
  skip_list =list()
  
  compare_temp = array(dim = length(stimCode)) # array for inner loop
  
  #for each line in the java code
  for(i in seq_along(stimCode))
  {
    compare_temp[] <- 0
    # for each line in the user code
    for(j in seq_along(userCode))
    {
        # compare the line of java code to the user line and store in array using LD 
        #(smallest number means more similar)
        compare_temp[j] = stringdist(stimCode[i], userCode[j], method = "lv")
    }
    #the user code line with the smallest LD
  
    #print("compare_temp")  
    #print(compare_temp)
      
      smallestIndexes = which(compare_temp == min(compare_temp))
     # print("smallestIndexes")
      #print(smallestIndexes)
      
      for(k in seq_along(smallestIndexes))
      {
        #print("smallestIndexes[k]")
        #print(smallestIndexes[k]) 
        #print("skip_list")
        #print(skip_list)
        
        #print("k")
        #print(k)
        if(smallestIndexes[k] %in% skip_list )
        {
          next
        }
        else
        {
          smallestIndex = smallestIndexes[k]
          #print("smallestIndex final")
          #print(smallestIndex)
          break
        }
      }
      
    
      mapping[i] = smallestIndex 
      final_LDs[smallestIndex] = compare_temp[smallestIndex]
      max_len <- pmax(nchar(stimCode[i]), nchar(userCode[j]))
      normalfinal_LDs[smallestIndex] = final_LDs[smallestIndex] / max_len  
      
      matchedStimuli[i] = 1
      matchedUserCode[smallestIndex] = 1
      skip_list = append(skip_list, smallestIndex)
      
      #reset variable
      smallestIndex= 0
      
   
  }
   
  
   final_LDs[is.na(final_LDs)] <- 0
   normalfinal_LDs[is.na(normalfinal_LDs)] <- 0
  
   print("mapping")
   print(mapping)
   print("final_LDs")
   print(final_LDs)
   print("normalfinal_LDs")
   print(normalfinal_LDs)
   print(matchedStimuli)
   print(matchedUserCode)
  
   
  
   
  missinglines = sum(matchedStimuli == 0 )
  extralines = sum(matchedUserCode == 0 )
  
  print(missinglines)
  print(extralines)
  
  errorlines = sum(extralines)
  
  if(errorlines > 0)
  {
    normalfinal_LDs = c(normalfinal_LDs, rep(1, errorlines)) 
  }
  #calculate the LD average
  
  LDAvg = mean(normalfinal_LDs)
  print("LDAvg")
  print(LDAvg)
  
  output = list(LDAvg, mapping)
  print("output")
  print(output)

  return(output) 
}



```

```{r Formula to Calculate Spearman's Footrule for line order }

calculate_sfr <- function(stimRank, userRank)
{

   sfr = TopKLists::Spearman(stimRank, userRank, length(stimRank), length(userRank), union(stimRank, userRank))
  
   k1 <- length(stimRank)
   k2 <- length(userRank)
   n  <- length(union(stimRank,userRank))
 
   #worst case scenario
   list1 <- 1:k1
   list2 <- rev(1:k2)
 
 
   D_max <- Spearman(list1, list2, k1, k2, n)
 
   normaldist = sfr/D_max
 
   print("sfr")
   print(sfr)
   print("D_max")
   print(D_max)
   print(normaldist)
   print("normaldist")
 
   return (normaldist)
  
}

```

```{r code }
#


 
   
# 
# 
# TestCode = c("while (temp != 0) {",
#              "if (number1 < number2) {",
#              "temp = number1;",
#              "number1 = number2;",
#              "number2 = temp;",
#              "}")
# 
# ParticCode = c("while (temp != 0) {",
#              "if (number1 > number2) {",
#              "number1 = number2;",
#              "temp = number1;",
#              "sum = 5 + 4",
#              "}")
# 
# calculate_levdist(TestCode, ParticCode)
# 
# 
# 
# 
# test1 = stringdist("if (number1 < number2) {", "if (number1 > number2) {", method = "lv")
# print(test1)
# max_len <- pmax(nchar("if (number1 < number2) {"), nchar("if (number1 > number2) {"))
# test1 / max_len
# 
# test2 = stringdist("while (temp != 0) {", "if (number1 < number2) {", method = "lv")
# print(test2)
# max_len2 <- pmax(nchar("while (temp != 0) {"), nchar("if (number1 < number2) {"))
# test2 / max_len2
# 
# 
# 
# 
# test2 = stringdist("while (temp != 0) {", "}", method = "lv")
# print(test2)
# max_len2 <- pmax(nchar("while (temp != 0) {"), nchar("}"))
# test2 / max_len2
# 
# 
# vec = c(1, 2, 3, 4, 5, 6)
# vec2 = c(1, 2, 4, 3, 7, 6)
# 
# dist = Spearman(vec, vec2, 6, 6, 7)
# 
# 
# k1 <- length(vec)
# k2 <- length(vec2)
# n  <- length(union(vec,vec2))
# 
# list1 <- 1:k1
# list2 <- rev(1:k2)
# 
# 
# D_max <- Spearman(list1, list2, k1, k2, n)
# 
# normaldist = dist/D_max
# 
# print(dist)
# print(D_max)
# print(normaldist) 


# 

```

```{r loop and calculate all the things }



mckData$X1_lev = NA
mckData$X1_mapping = NA
mckData$X2_sfr = NA
mckData$X2_total_acc = NA

mckData$X2_lev = NA
mckData$X2_mapping = NA
mckData$X1_sfr = NA
mckData$X1_total_acc = NA

mckData$X3_lev = NA
mckData$X3_mapping = NA
mckData$X3_sfr = NA
mckData$X3_total_acc = NA


mckData$X4_lev = NA
mckData$X4_mapping = NA
mckData$X4_sfr = NA
mckData$X4_total_acc = NA

mckData$X5_lev = NA
mckData$X5_mapping = NA
mckData$X5_sfr = NA
mckData$X5_total_acc = NA


##timepoint 1
for(i in 1:length(mckData$X1_code.recall.control)) 
{
  print("loop number:")
  print(i)
  if(mckData$X1_code.recall.control[i] != "" &&  !is.na(mckData$X1_code.recall.control[i]))
  {
    print("not empty!")
    #extract into a vector
    userCode = mckData[ i, "X1_code.recall.control"]
    parts <- strsplit(userCode, split = "\n")
    userCodeVec = unlist(parts)
    
    if(mckData$LangChoice[i] == "Java"){
      
      lev_dat = calculate_levdist(stimCode = javaCode, userCode = userCodeVec)
      mckData$X1_lev[i] = lev_dat[[1]]
      mckData$X1_mapping[i] = list(lev_dat[2])
      #convert list to vector
      vecMapping = unlist(mckData$X1_mapping[i])
      mckData$X1_sfr[i] = calculate_sfr(javaRank, vecMapping)
      mckData$X1_total_acc[i] = (mckData$X1_lev[i] +  mckData$X1_sfr[i]) /2
  
    }
    else if(mckData$LangChoice[i] == "Python"){
      lev_dat = calculate_levdist(stimCode = pythonCode, userCode = userCodeVec)
      mckData$X1_lev[i] = lev_dat[[1]]
      mckData$X1_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X1_mapping[i])
      mckData$X1_sfr[i] = calculate_sfr(pythonRank , vecMapping)
      mckData$X1_total_acc[i] = (mckData$X1_lev[i] +  mckData$X1_sfr[i]) /2
    }
    else if(mckData$LangChoice[i] == "C++"){
      lev_dat = calculate_levdist(stimCode = cCode, userCode = userCodeVec)
      mckData$X1_lev[i] = lev_dat[[1]]
      mckData$X1_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X1_mapping[i])
      mckData$X1_sfr[i] = calculate_sfr(cRank , vecMapping)
      mckData$X1_total_acc[i] = (mckData$X1_lev[i] +  mckData$X1_sfr[i]) /2
    }
    else
    {
      print("Error, no language choice detected")
    }
    
  }
}

##timepoint 2
for(i in 1:length(mckData$X2_code.recall.control)) 
{
  print("loop number:")
  print(i)
  if(mckData$X2_code.recall.control[i] != "" &&  !is.na(mckData$X2_code.recall.control[i]))
  {
    print("not empty!")
    #extract into a vector
    userCode = mckData[ i, "X2_code.recall.control"]
    parts <- strsplit(userCode, split = "\n")
    userCodeVec = unlist(parts)
    
    if(mckData$LangChoice[i] == "Java"){
      
      lev_dat = calculate_levdist(stimCode = javaCode, userCode = userCodeVec)
      mckData$X2_lev[i] = lev_dat[[1]]
      mckData$X2_mapping[i] = list(lev_dat[2])
      #convert list to vector
      vecMapping = unlist(mckData$X2_mapping[i])
      mckData$X2_sfr[i] = calculate_sfr(javaRank, vecMapping)
      mckData$X2_total_acc[i] = (mckData$X2_lev[i] +  mckData$X2_sfr[i]) /2
  
    }
    else if(mckData$LangChoice[i] == "Python"){
      lev_dat = calculate_levdist(stimCode = pythonCode, userCode = userCodeVec)
      mckData$X2_lev[i] = lev_dat[[1]]
      mckData$X2_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X2_mapping[i])
      mckData$X2_sfr[i] = calculate_sfr(pythonRank , vecMapping)
      mckData$X2_total_acc[i] = (mckData$X2_lev[i] +  mckData$X2_sfr[i]) /2
    }
    else if(mckData$LangChoice[i] == "C++"){
      lev_dat = calculate_levdist(stimCode = cCode, userCode = userCodeVec)
      mckData$X2_lev[i] = lev_dat[[1]]
      mckData$X2_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X2_mapping[i])
      mckData$X2_sfr[i] = calculate_sfr(cRank , vecMapping)
      mckData$X2_total_acc[i] = (mckData$X2_lev[i] +  mckData$X2_sfr[i]) /2
    }
    else
    {
      print("Error, no language choice detected")
    }
    
  }
}

##timepoint 3
for(i in 1:length(mckData$X3_code.recall.control)) 
{
  print("loop number:")
  print(i)
  if(mckData$X3_code.recall.control[i] != "" &&  !is.na(mckData$X3_code.recall.control[i]))
  {
    print("not empty!")
    #extract into a vector
    userCode = mckData[ i, "X3_code.recall.control"]
    parts <- strsplit(userCode, split = "\n")
    userCodeVec = unlist(parts)
    
    if(mckData$LangChoice[i] == "Java"){
      
      lev_dat = calculate_levdist(stimCode = javaCode, userCode = userCodeVec)
      mckData$X3_lev[i] = lev_dat[[1]]
      mckData$X3_mapping[i] = list(lev_dat[2])
      #convert list to vector
      vecMapping = unlist(mckData$X3_mapping[i])
      mckData$X3_sfr[i] = calculate_sfr(javaRank, vecMapping)
      mckData$X3_total_acc[i] = (mckData$X3_lev[i] +  mckData$X3_sfr[i]) /2
  
    }
    else if(mckData$LangChoice[i] == "Python"){
      lev_dat = calculate_levdist(stimCode = pythonCode, userCode = userCodeVec)
      mckData$X3_lev[i] = lev_dat[[1]]
      mckData$X3_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X3_mapping[i])
      mckData$X3_sfr[i] = calculate_sfr(pythonRank , vecMapping)
      mckData$X3_total_acc[i] = (mckData$X3_lev[i] +  mckData$X3_sfr[i]) /2
    }
    else if(mckData$LangChoice[i] == "C++"){
      lev_dat = calculate_levdist(stimCode = cCode, userCode = userCodeVec)
      mckData$X3_lev[i] = lev_dat[[1]]
      mckData$X3_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X3_mapping[i])
      mckData$X3_sfr[i] = calculate_sfr(cRank , vecMapping)
      mckData$X3_total_acc[i] = (mckData$X3_lev[i] +  mckData$X3_sfr[i]) /2
    }
    else
    {
      print("Error, no language choice detected")
    }
    
  }
}
##timepoint 4
for(i in 1:length(mckData$X4_code.recall.control)) 
{
  print("loop number:")
  print(i)
  if(mckData$X4_code.recall.control[i] != "" &&  !is.na(mckData$X4_code.recall.control[i]))
  {
    print("not empty!")
    #extract into a vector
    userCode = mckData[ i, "X4_code.recall.control"]
    parts <- strsplit(userCode, split = "\n")
    userCodeVec = unlist(parts)
    
    if(mckData$LangChoice[i] == "Java"){
      
      lev_dat = calculate_levdist(stimCode = javaCode, userCode = userCodeVec)
      mckData$X4_lev[i] = lev_dat[[1]]
      mckData$X4_mapping[i] = list(lev_dat[2])
      #convert list to vector
      vecMapping = unlist(mckData$X4_mapping[i])
      mckData$X4_sfr[i] = calculate_sfr(javaRank, vecMapping)
      mckData$X4_total_acc[i] = (mckData$X4_lev[i] +  mckData$X4_sfr[i]) /2
  
    }
    else if(mckData$LangChoice[i] == "Python"){
      lev_dat = calculate_levdist(stimCode = pythonCode, userCode = userCodeVec)
      mckData$X4_lev[i] = lev_dat[[1]]
      mckData$X4_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X4_mapping[i])
      mckData$X4_sfr[i] = calculate_sfr(pythonRank , vecMapping)
      mckData$X4_total_acc[i] = (mckData$X4_lev[i] +  mckData$X4_sfr[i]) /2
    }
    else if(mckData$LangChoice[i] == "C++"){
      lev_dat = calculate_levdist(stimCode = cCode, userCode = userCodeVec)
      mckData$X4_lev[i] = lev_dat[[1]]
      mckData$X4_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X4_mapping[i])
      mckData$X4_sfr[i] = calculate_sfr(cRank , vecMapping)
      mckData$X4_total_acc[i] = (mckData$X4_lev[i] +  mckData$X4_sfr[i]) /2
    }
    else
    {
      print("Error, no language choice detected")
    }
    
  }
}
##timepoint 5
for(i in 1:length(mckData$X5_code.recall.control)) 
{
  print("loop number:")
  print(i)
  if(mckData$X5_code.recall.control[i] != "" &&  !is.na(mckData$X5_code.recall.control[i]))
  {
    print("not empty!")
    #extract into a vector
    userCode = mckData[ i, "X5_code.recall.control"]
    parts <- strsplit(userCode, split = "\n")
    userCodeVec = unlist(parts)
    
    if(mckData$LangChoice[i] == "Java"){
      
      lev_dat = calculate_levdist(stimCode = javaCode, userCode = userCodeVec)
      mckData$X5_lev[i] = lev_dat[[1]]
      mckData$X5_mapping[i] = list(lev_dat[2])
      #convert list to vector
      vecMapping = unlist(mckData$X5_mapping[i])
      mckData$X5_sfr[i] = calculate_sfr(javaRank, vecMapping)
      mckData$X5_total_acc[i] = (mckData$X5_lev[i] +  mckData$X5_sfr[i]) /2
  
    }
    else if(mckData$LangChoice[i] == "Python"){
      lev_dat = calculate_levdist(stimCode = pythonCode, userCode = userCodeVec)
      mckData$X5_lev[i] = lev_dat[[1]]
      mckData$X5_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X5_mapping[i])
      mckData$X5_sfr[i] = calculate_sfr(pythonRank , vecMapping)
      mckData$X5_total_acc[i] = (mckData$X5_lev[i] +  mckData$X5_sfr[i]) /2
    }
    else if(mckData$LangChoice[i] == "C++"){
      lev_dat = calculate_levdist(stimCode = cCode, userCode = userCodeVec)
      mckData$X5_lev[i] = lev_dat[[1]]
      mckData$X5_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X5_mapping[i])
      mckData$X5_sfr[i] = calculate_sfr(cRank , vecMapping)
      mckData$X5_total_acc[i] = (mckData$X5_lev[i] +  mckData$X5_sfr[i]) /2
    }
    else
    {
      print("Error, no language choice detected")
    }
    
  }
}



###################################Experimental##################

##timepoint 1
for(i in 1:length(mckData$X1_Code.Recall.Exp.)) 
{
  print("loop number:")
  print(i)
  if(mckData$X1_Code.Recall.Exp.[i] != "" &&  !is.na(mckData$X1_Code.Recall.Exp.[i]))
  {
    print("not empty!")
    #extract into a vector
    userCode = mckData[ i, "X1_Code.Recall.Exp."]
    parts <- strsplit(userCode, split = "\n")
    userCodeVec = unlist(parts)
    
    if(mckData$LangChoice[i] == "Java"){
      
      lev_dat = calculate_levdist(stimCode = javaScramble, userCode = userCodeVec)
      mckData$X1_lev[i] = lev_dat[[1]]
      mckData$X1_mapping[i] = list(lev_dat[2])
      #convert list to vector
      vecMapping = unlist(mckData$X1_mapping[i])
      mckData$X1_sfr[i] = calculate_sfr(javaRank, vecMapping)
      mckData$X1_total_acc[i] = (mckData$X1_lev[i] +  mckData$X1_sfr[i]) /2
  
    }
    else if(mckData$LangChoice[i] == "Python"){
      lev_dat = calculate_levdist(stimCode = pythonScramble, userCode = userCodeVec)
      mckData$X1_lev[i] = lev_dat[[1]]
      mckData$X1_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X1_mapping[i])
      mckData$X1_sfr[i] = calculate_sfr(pythonRank , vecMapping)
      mckData$X1_total_acc[i] = (mckData$X1_lev[i] +  mckData$X1_sfr[i]) /2
    }
    else if(mckData$LangChoice[i] == "C++"){
      lev_dat = calculate_levdist(stimCode = cScramble, userCode = userCodeVec)
      mckData$X1_lev[i] = lev_dat[[1]]
      mckData$X1_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X1_mapping[i])
      mckData$X1_sfr[i] = calculate_sfr(cRank , vecMapping)
      mckData$X1_total_acc[i] = (mckData$X1_lev[i] +  mckData$X1_sfr[i]) /2
    }
    else
    {
      print("Error, no language choice detected")
    }
    
  }
}


##timepoint 2
for(i in 1:length(mckData$X2_Code.Recall.Exp.)) 
{
  print("loop number:")
  print(i)
  if(mckData$X2_Code.Recall.Exp.[i] != "" &&  !is.na(mckData$X2_Code.Recall.Exp.[i]))
  {
    print("not empty!")
    #extract into a vector
    userCode = mckData[ i, "X2_Code.Recall.Exp."]
    parts <- strsplit(userCode, split = "\n")
    userCodeVec = unlist(parts)
    
    if(mckData$LangChoice[i] == "Java"){
      
      lev_dat = calculate_levdist(stimCode = javaScramble, userCode = userCodeVec)
      mckData$X2_lev[i] = lev_dat[[1]]
      mckData$X2_mapping[i] = list(lev_dat[2])
      #convert list to vector
      vecMapping = unlist(mckData$X2_mapping[i])
      mckData$X2_sfr[i] = calculate_sfr(javaRank, vecMapping)
      mckData$X2_total_acc[i] = (mckData$X2_lev[i] +  mckData$X2_sfr[i]) /2
  
    }
    else if(mckData$LangChoice[i] == "Python"){
      lev_dat = calculate_levdist(stimCode = pythonScramble, userCode = userCodeVec)
      mckData$X2_lev[i] = lev_dat[[1]]
      mckData$X2_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X2_mapping[i])
      mckData$X2_sfr[i] = calculate_sfr(pythonRank , vecMapping)
      mckData$X2_total_acc[i] = (mckData$X2_lev[i] +  mckData$X2_sfr[i]) /2
    }
    else if(mckData$LangChoice[i] == "C++"){
      lev_dat = calculate_levdist(stimCode = cScramble, userCode = userCodeVec)
      mckData$X2_lev[i] = lev_dat[[1]]
      mckData$X2_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X2_mapping[i])
      mckData$X2_sfr[i] = calculate_sfr(cRank , vecMapping)
      mckData$X2_total_acc[i] = (mckData$X2_lev[i] +  mckData$X2_sfr[i]) /2
    }
    else
    {
      print("Error, no language choice detected")
    }
    
  }
}

##timepoint 3
for(i in 1:length(mckData$X3_Code.Recall.Exp.)) 
{
  print("loop number:")
  print(i)
  if(mckData$X3_Code.Recall.Exp.[i] != "" &&  !is.na(mckData$X3_Code.Recall.Exp.[i]))
  {
    print("not empty!")
    #extract into a vector
    userCode = mckData[ i, "X3_Code.Recall.Exp."]
    parts <- strsplit(userCode, split = "\n")
    userCodeVec = unlist(parts)
    
    if(mckData$LangChoice[i] == "Java"){
      
      lev_dat = calculate_levdist(stimCode = javaScramble, userCode = userCodeVec)
      mckData$X3_lev[i] = lev_dat[[1]]
      mckData$X3_mapping[i] = list(lev_dat[2])
      #convert list to vector
      vecMapping = unlist(mckData$X3_mapping[i])
      mckData$X3_sfr[i] = calculate_sfr(javaRank, vecMapping)
      mckData$X3_total_acc[i] = (mckData$X3_lev[i] +  mckData$X3_sfr[i]) /2
  
    }
    else if(mckData$LangChoice[i] == "Python"){
      lev_dat = calculate_levdist(stimCode = pythonScramble, userCode = userCodeVec)
      mckData$X3_lev[i] = lev_dat[[1]]
      mckData$X3_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X3_mapping[i])
      mckData$X3_sfr[i] = calculate_sfr(pythonRank , vecMapping)
      mckData$X3_total_acc[i] = (mckData$X3_lev[i] +  mckData$X3_sfr[i]) /2
    }
    else if(mckData$LangChoice[i] == "C++"){
      lev_dat = calculate_levdist(stimCode = cScramble, userCode = userCodeVec)
      mckData$X3_lev[i] = lev_dat[[1]]
      mckData$X3_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X3_mapping[i])
      mckData$X3_sfr[i] = calculate_sfr(cRank , vecMapping)
      mckData$X3_total_acc[i] = (mckData$X3_lev[i] +  mckData$X3_sfr[i]) /2
    }
    else
    {
      print("Error, no language choice detected")
    }
    
  }
}


##timepoint 4
for(i in 1:length(mckData$X4_Code.Recall.Exp.)) 
{
  print("loop number:")
  print(i)
  if(mckData$X4_Code.Recall.Exp.[i] != "" &&  !is.na(mckData$X4_Code.Recall.Exp.[i]))
  {
    print("not empty!")
    #extract into a vector
    userCode = mckData[ i, "X4_Code.Recall.Exp."]
    parts <- strsplit(userCode, split = "\n")
    userCodeVec = unlist(parts)
    
    if(mckData$LangChoice[i] == "Java"){
      
      lev_dat = calculate_levdist(stimCode = javaScramble, userCode = userCodeVec)
      mckData$X4_lev[i] = lev_dat[[1]]
      mckData$X4_mapping[i] = list(lev_dat[2])
      #convert list to vector
      vecMapping = unlist(mckData$X4_mapping[i])
      mckData$X4_sfr[i] = calculate_sfr(javaRank, vecMapping)
      mckData$X4_total_acc[i] = (mckData$X4_lev[i] +  mckData$X4_sfr[i]) /2
  
    }
    else if(mckData$LangChoice[i] == "Python"){
      lev_dat = calculate_levdist(stimCode = pythonScramble, userCode = userCodeVec)
      mckData$X4_lev[i] = lev_dat[[1]]
      mckData$X4_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X4_mapping[i])
      mckData$X4_sfr[i] = calculate_sfr(pythonRank , vecMapping)
      mckData$X4_total_acc[i] = (mckData$X4_lev[i] +  mckData$X4_sfr[i]) /2
    }
    else if(mckData$LangChoice[i] == "C++"){
      lev_dat = calculate_levdist(stimCode = cScramble, userCode = userCodeVec)
      mckData$X4_lev[i] = lev_dat[[1]]
      mckData$X4_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X4_mapping[i])
      mckData$X4_sfr[i] = calculate_sfr(cRank , vecMapping)
      mckData$X4_total_acc[i] = (mckData$X4_lev[i] +  mckData$X4_sfr[i]) /2
    }
    else
    {
      print("Error, no language choice detected")
    }
    
  }
}

##timepoint 5
for(i in 1:length(mckData$X5_Code.Recall.Exp.)) 
{
  print("loop number:")
  print(i)
  if(mckData$X5_Code.Recall.Exp.[i] != "" &&  !is.na(mckData$X5_Code.Recall.Exp.[i]))
  {
    print("not empty!")
    #extract into a vector
    userCode = mckData[ i, "X5_Code.Recall.Exp."]
    parts <- strsplit(userCode, split = "\n")
    userCodeVec = unlist(parts)
    
    if(mckData$LangChoice[i] == "Java"){
      
      lev_dat = calculate_levdist(stimCode = javaScramble, userCode = userCodeVec)
      mckData$X5_lev[i] = lev_dat[[1]]
      mckData$X5_mapping[i] = list(lev_dat[2])
      #convert list to vector
      vecMapping = unlist(mckData$X5_mapping[i])
      mckData$X5_sfr[i] = calculate_sfr(javaRank, vecMapping)
      mckData$X5_total_acc[i] = (mckData$X5_lev[i] +  mckData$X5_sfr[i]) /2
  
    }
    else if(mckData$LangChoice[i] == "Python"){
      lev_dat = calculate_levdist(stimCode = pythonScramble, userCode = userCodeVec)
      mckData$X5_lev[i] = lev_dat[[1]]
      mckData$X5_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X5_mapping[i])
      mckData$X5_sfr[i] = calculate_sfr(pythonRank , vecMapping)
      mckData$X5_total_acc[i] = (mckData$X5_lev[i] +  mckData$X5_sfr[i]) /2
    }
    else if(mckData$LangChoice[i] == "C++"){
      lev_dat = calculate_levdist(stimCode = cScramble, userCode = userCodeVec)
      mckData$X5_lev[i] = lev_dat[[1]]
      mckData$X5_mapping[i] = list(lev_dat[2])
      
      #convert list to vector
      vecMapping = unlist(mckData$X5_mapping[i])
      mckData$X5_sfr[i] = calculate_sfr(cRank , vecMapping)
      mckData$X5_total_acc[i] = (mckData$X5_lev[i] +  mckData$X5_sfr[i]) /2
    }
    else
    {
      print("Error, no language choice detected")
    }
    
  }
}

```
```{r Average performance}

#avg lv dist over 5 trials
mckData$overall_lev = (mckData$X1_lev + mckData$X2_lev + mckData$X3_lev + mckData$X4_lev +mckData$X5_lev) / 5

#avg footrule over 5 trials
mckData$overall_sfr = (mckData$X1_sfr + mckData$X2_sfr + mckData$X3_sfr + mckData$X4_sfr +mckData$X5_sfr) / 5

#average total acc over 5 trials

mckData$overall_total_acc = (mckData$X1_total_acc + mckData$X2_total_acc + mckData$X3_total_acc + mckData$X4_total_acc +mckData$X5_total_acc) / 5


```

```{r control or experimental condition }

mckData$Condition <- NA

mckData$Condition[!is.na(mckData$X1_Code.Recall.Exp.) &mckData$X1_Code.Recall.Exp. != ""] <- "Experimental"

mckData$Condition[!is.na(mckData$X1_code.recall.control) &mckData$X1_code.recall.control != ""] <- "Control"
```

```{r Descriptives }


#pull out items we want descriptive statistics for
mckData$gender = as.factor(mckData$gender)
mckData$race.eth = as.factor(mckData$race.eth)
mckData$Expertise = as.factor(mckData$Expertise)


descriptives =  subset(mckData, select = c(gender,
                                           race.eth,
                                           age,
                                           Experience.months,
                                           Expertise,
                                           LangChoice,
                                           Primary.Language,
                                           self_exp_num,
                                           CPSES_COMP,
                                           PAS_COMP,
                                           MA_COMP,
                                           MIND_COMP,
                                           torr_sum,
                                           overall_lev, 
                                           overall_sfr,
                                           overall_total_acc))

descriptives$race.eth = as.factor(descriptives$race.eth)

#descriptives = drop_na(descriptives)

Hmisc::describe(descriptives)

descriptivesforSD =  subset(mckData, select = c(self_exp_num,
                                                Experience.months,
                                                 CPSES_COMP,
                                                 PAS_COMP,
                                                 MA_COMP,
                                                 MIND_COMP,
                                                 torr_sum,
                                                 overall_lev, 
                                                 overall_sfr,
                                                 overall_total_acc))

table(descriptives$race.eth)

prop.table(table(descriptives$race.eth))  # For proportions

psych::describe(descriptivesforSD)



```
```{r Correlations }

#grab only the things we want to correlate
correlation_variables <- subset(mckData, select = c(Experience.months,
                                                    self_exp_num,
                                                    CPSES_COMP,
                                                    PAS_COMP,
                                                    MA_COMP,
                                                    MIND_COMP,
                                                    torr_sum,
                                                    overall_lev, 
                                                    overall_sfr,
                                                    overall_total_acc))
                                                    

#remove rows with one or more N/As
###correlation_variables <- correlation_variables[complete.cases(correlation_variables), ]
#nrow(correlation_variables)

rcorr(as.matrix(correlation_variables), type = "pearson")




```

```{r plotting}
# Control condition
ggplot(
  filter(mckData, Condition == "Control"),
  aes(x = Experience.months, y = overall_total_acc)
) +
  geom_point(alpha = .7) +
  geom_smooth(method = "lm", se = TRUE) +
  labs(
    title = "Control Condition",
    x = "Programming Experience (Months)",
    y = "Total Accuracy"
  ) +
  theme_minimal()

# Experimental condition
ggplot(
  filter(mckData, Condition == "Experimental"),
  aes(x = Experience.months, y = overall_total_acc)
) +
  geom_point(alpha = .7) +
  geom_smooth(method = "lm", se = TRUE) +
  labs(
    title = "Experimental Condition",
    x = "Programming Experience (Months)",
    y = "Total Accuracy"
  ) +
  theme_minimal()

```


